
// 预览页可能以 data: URL 加载(opaque origin),那时 localStorage 会抛 SecurityError,
// app.js 的顶层执行会就此中断。垫一个内存版,行为够用。
(function () {
  var mem = {};
  try { window.localStorage.getItem('probe'); return; } catch (e) {}
  Object.defineProperty(window, 'localStorage', {
    value: {
      getItem: function (k) { return k in mem ? mem[k] : null; },
      setItem: function (k, v) { mem[k] = String(v); },
      removeItem: function (k) { delete mem[k]; },
      clear: function () { mem = {}; },
    },
    configurable: true,
  });
})();


// ---- 假的 contextBridge:形状照着真的来,数据挑典型值 ----------------------
const RECORDS = [
  {id:'r1', symbol:'NVDA', action:'BUY', quantity:2, account:'富途模拟', account_masked:'20***585', is_paper:true, status:'Submitted',
   final_status:'filled', avg_fill_price:5.52, created_at:'2026-08-21T13:41:02Z',
   intent_summary:'限价 5.5 买入 2 张 NVDA 20260821 180 Call', reason:'财报前布局',
   raw_instruction:'买2张英伟达周五180call 限价5.5'},
  {id:'r2', symbol:'AAPL', action:'BUY', quantity:100, account:'富途模拟', account_masked:'20***585', is_paper:true, status:'Submitted',
   final_status:null, created_at:'2026-08-21T13:38:55Z',
   intent_summary:'限价 316 买入 100 股 AAPL', reason:'回调到位', raw_instruction:'苹果316买100股'},
  {id:'r3', symbol:'SPY', action:'SELL', quantity:1, account:'富途模拟', account_masked:'20***585', is_paper:true,
   final_status:'ibkr_error', created_at:'2026-08-21T13:20:10Z',
   intent_summary:'市价卖出 1 张 SPY Put', reason:'止损',
   rejection:{code:'FUTU_ERROR'}, raw_instruction:'把spy的put平了'},
  {id:'r4', symbol:'TSLA', action:'BUY', quantity:50, account:'富途模拟', account_masked:'20***585', is_paper:true,
   final_status:'rejected_by_validator', created_at:'2026-08-21T12:02:00Z',
   intent_summary:'市价买入 50 股 TSLA', reason:'突破', raw_instruction:'特斯拉市价来50股'},
];
const MACRO = {rows:[
  {key:'spx', label:'标普500', instrument:'SPY', last:766.78, change_pct:-0.30, source:'futu'},
  {key:'ndx', label:'纳指100', instrument:'QQQ', last:717.08, change_pct:-0.06, source:'futu'},
  {key:'dji', label:'道指', instrument:'DIA', last:452.19, change_pct:0.12, source:'futu'},
  {key:'rut', label:'罗素2000', instrument:'IWM', last:241.55, change_pct:-0.84, source:'futu'},
  {key:'vix', label:'VIX', instrument:'VIX', last:14.62, change_pct:3.11, source:'public'},
  {key:'us10y', label:'10年美债', instrument:'US10Y', last:4.183, change_pct:-0.41, source:'public'},
  {key:'dxy', label:'美元指数', instrument:'DXY', last:98.42, change_pct:0.08, source:'public'},
  {key:'gold', label:'黄金', instrument:'GLD', last:312.44, change_pct:0.55, source:'futu'},
], fetched_at:'2026-08-21T13:42:00Z'};

window.dafri = {
  platform: 'win32',
  status: async () => ({
    protocol:'1.0', now_et:'2026-08-21 09:42:11', market_status:'盘中',
    prompt_version:'v1.7.0', prompt_fingerprint:'a3f9', model:'claude-opus-5',
    auto_execute:true, allow_live_trading:false,
    breaker:{engaged:false, reason:'', consecutive_failures:0},
    broker_provider:'futu', broker_connected:true, broker_upstream_ok:true,
    pending_count:1,
    accounts:[{alias:'模拟',account_masked:'DU***321',is_paper:true,connection:'paper',default:true},
              {alias:'主账户',account_masked:'U1***567',is_paper:false,connection:'live'},
              {alias:'富途模拟',account_masked:'20***585',is_paper:true,connection:'opend'}],
    limits:{max_order_notional:5000,max_option_contracts:5,max_mkt_shares:200,
            min_confidence:0.9,max_spread_slippage:0.1,duplicate_window_minutes:10},
  }),
  selftest: async () => ({prompt_version:'v1.7.0', prompt_fingerprint:'a3f9c1', system_prompt_chars:8421,
    fewshot_pairs:7, symbol_aliases:{苹果:'AAPL',英伟达:'NVDA'}, accounts:[]}),
  listRecords: async () => ({records:RECORDS}),
  // 详情要拿完整记录(store 折叠事件之后的那份),不是列表里的摘要
  getRecord: async (id) => ({record:{
    id:id||'r1', created_at:'2026-08-21T13:41:02Z',
    input:{raw_instruction:'买2张英伟达周五180call 限价5.5', reason:'财报前布局', input_channel:'manual'},
    llm:{model:'claude-opus-5', prompt_version:'v1.7.0', prompt_fingerprint:'a3f9c1',
         intent_summary:'限价 5.5 买入 2 张 NVDA 20260821 180 Call', confidence:0.97,
         warnings:[], usage:{input_tokens:3120, output_tokens:210}},
    execution_type:'IMMEDIATE', trigger:null,
    account:{alias:'富途模拟', account_masked:'20***585', is_paper:true},
    contract:{secType:'OPT', symbol:'NVDA', lastTradeDateOrContractMonth:'20260821',
              strike:180, right:'C', multiplier:'100'},
    order:{action:'BUY', orderType:'LMT', totalQuantity:2, price_mode:'EXPLICIT',
           lmtPrice:5.5, tif:'DAY', outsideRth:false},
    ibkr:{order_id:1, perm_id:1, avg_fill_price:5.52, total_commission:1.3,
      status_timeline:[{status:'PreSubmitted', at:'2026-08-21T13:41:03Z'},
                       {status:'Submitted', at:'2026-08-21T13:41:04Z'},
                       {status:'Filled', at:'2026-08-21T13:41:09Z'}],
      fills:[{exec_id:'D-1', time:'2026-08-21T13:41:09Z', qty:1, price:5.51, commission:0.65},
             {exec_id:'D-2', time:'2026-08-21T13:41:09Z', qty:1, price:5.53, commission:0.65}]},
    final_status:'filled',
    post_warnings:[{message:'AUTO_MID 定价:盘口中间价 ± 滑点上限', at:'2026-08-21T13:41:02Z'}]}}),
  listPending: async () => ({pending:[{record_id:'p1', intent_summary:'SPY 涨到 775 时买入 100 股',
    symbol:'SPY', operator:'>=', value:775, account:'富途模拟', account_masked:'20***585', is_paper:true, created_at:'2026-08-21T13:30:00Z'}]}),
  pollPending: async () => ({fired:[], prices:{}, synced:0}),
  // 注意:引擎是**平铺**返回的,没有外层 settings 包装(见 rpc.settings_get)
  getSettings: async () => ({path:'config/settings.json',
    llm:{model:'claude-opus-5',effort:'high',max_tokens:8000},
    limits:{max_order_notional:5000,max_option_contracts:5,
      max_mkt_shares:200,min_confidence:0.9,max_spread_slippage:0.1,max_orders_per_input:5,
      duplicate_window_minutes:10,duplicate_qty_tolerance:0.2},
    policies:{auto_execute:true,allow_live_trading:false,require_trigger_price_verification:true,
      trigger_min_gap_bps:5,closed_market_policy:'reject_market_orders',
      consecutive_failure_breaker:3,review_feature_enabled:false},
    symbol_aliases:{苹果:'AAPL',英伟达:'NVDA'}, accounts:[], connections:{}}),
  breakerState: async () => ({engaged:false, reason:'', consecutive_failures:0}),
  listIdeas: async () => ({ideas:[
    {id:'i1', text:'AXTI 周五尾盘买入,量能起来了', status:'active', symbols:['AXTI'], created_at:'2026-08-20T20:00:00Z'},
    {id:'i2', text:'留意 SPY 770 这个整数关口', status:'done', symbols:['SPY'], created_at:'2026-08-19T14:00:00Z'}]}),
  addIdea: async () => ({idea:{}}), updateIdea: async () => ({}), analyzeIdea: async () => ({}),
  listSectors: async () => ({sectors:[
    {id:'s1', name:'AI 算力', stocks:[{symbol:'NVDA',company:'英伟达',reason:'龙头'},
      {symbol:'AMD',company:'超威',reason:'追赶者'},{symbol:'AVGO',company:'博通',reason:'定制芯片'}]},
    {id:'s2', name:'核电', stocks:[{symbol:'CEG',company:'星座能源',reason:'数据中心供电'},
      {symbol:'VST',company:'Vistra',reason:'同上'}]}]}),
  sectorQuotes: async () => ({connected:true, quotes:{
    NVDA:{last:219.74,close:219.74,change_pct:0}, AMD:{last:242.1,close:238.0,change_pct:1.72},
    AVGO:{last:388.5,close:392.2,change_pct:-0.94}, CEG:{last:341.2,close:335.5,change_pct:1.70},
    VST:{last:208.8,close:211.0,change_pct:-1.04}}}),
  addSector: async()=>({}), deleteSector: async()=>({}), pickSector: async()=>({}),
  addSectorStock: async()=>({}), removeSectorStock: async()=>({}),
  appInfo: async () => ({version:'0.2.0', electron:'40.0.0', configPath:'config/settings.json',
    enginePath:'src/ibkr_agent', engineRunning:true}),
  llmCatalog: async () => ({providers:[
    {key:'anthropic',label:'Anthropic(Claude)',default_model:'claude-opus-5',
     models:['claude-opus-5','claude-sonnet-5','claude-haiku-4-5'],supports_effort:true,
     supports_temperature:false,needs_base_url:false,default_base_url:'',key_hint:'sk-ant-...',
     docs:'https://platform.claude.com/'},
    {key:'openai_compatible',label:'OpenAI 兼容端点',default_model:'',
     models:['deepseek-chat','qwen-max','glm-4-plus'],supports_effort:false,
     supports_temperature:true,needs_base_url:true,default_base_url:'https://api.deepseek.com/v1',
     key_hint:'sk-...',docs:'填服务商给的 base_url'}],
    current:{provider:'anthropic',model:'claude-opus-5',base_url:'',effort:'high',temperature:null,
      max_tokens:8000,timeout_s:60,keychain_service:'dafri-llm-api-key',keychain_account:'anthropic'},
    key_configured:{anthropic:true, openai_compatible:false}}),
  llmPatch: async()=>({}), llmTest: async()=>({ok:true, latency_ms:820, structured_mode:'json_schema'}),
  setApiKeyFor: async()=>({ok:true}),
  scanTws: async () => ({ports:[
    {port:7496,label:'TWS 实盘',kind:'tws',paper:false,open:false,error:'端口未监听',configured_as:'live'},
    {port:7497,label:'TWS 模拟',kind:'tws',paper:true,open:false,error:'端口未监听',configured_as:'paper'},
    {port:4001,label:'IB Gateway 实盘',kind:'gateway',paper:false,open:false,error:'端口未监听',configured_as:null},
    {port:4002,label:'IB Gateway 模拟',kind:'gateway',paper:true,open:false,error:'端口未监听',configured_as:null}],
    apps:[{key:'tws',name:'Trader Workstation',installed:false,paths:[],running:false},
          {key:'gateway',name:'IB Gateway',installed:false,paths:[],running:false}],
    guide:[{step:1,title:'启动 TWS 或 IB Gateway 并登录',detail:'在 IBKR 自己的窗口里输入账号密码。本软件不接触、也不保存你的 IBKR 凭证。'},
           {step:2,title:'打开 API 开关',detail:'TWS:Configure(齿轮)→ API → Settings,勾选「Enable ActiveX and Socket Clients」。'},
           {step:3,title:'核对 Socket port',detail:'同一页的「Socket port」要和本软件配置里的端口一致(当前配置:7497、7496)。'}],
    connections:{paper:{host:'127.0.0.1',port:7497,client_id:11},live:{host:'127.0.0.1',port:7496,client_id:12}},
    connected:[]}),
  diagnoseTws: async () => ({results:[{connection:'paper',host:'127.0.0.1',port:7497,port_open:false,
    connected:false,error:'端口 7497 拒绝连接',hint:'TWS / IB Gateway 没有在跑,或者它的 API 端口不是 7497。'}]}),
  launchTws: async()=>({launched:true}),
  brokerCatalog: async () => ({current:'futu', connected:['opend'], providers:[
    {key:'ibkr',label:'盈透证券(IBKR / TWS)',current:false,
     connections:{paper:{host:'127.0.0.1',port:7497,client_id:11},live:{host:'127.0.0.1',port:7496,client_id:12}},
     accounts:[{alias:'模拟',account_masked:'DU***321',is_paper:true,connection:'paper',default:true},
               {alias:'主账户',account_masked:'U1***567',is_paper:false,connection:'live'}],
     config_snippet:null},
    {key:'futu',label:'富途证券(OpenD)',current:true,
     connections:{opend:{host:'127.0.0.1',port:11111,client_id:11}},
     accounts:[{alias:'富途模拟',account_masked:'20***585',is_paper:true,connection:'opend'}],
     config_snippet:null}],
    futu:{trd_market:'US',security_firm:'FUTUSECURITIES',symbol_map:{},unlock_password_saved:false}}),
  selectBroker: async()=>({current:'futu',connections:['opend']}),
  scanFutu: async () => ({ports:[
    {port:11111,label:'OpenD API',kind:'opend',paper:null,open:true,latency_ms:14,configured_as:'opend'},
    {port:22222,label:'OpenD 控制台(telnet,仅供参考)',kind:'telnet',paper:null,open:false,error:'连接超时',configured_as:null}],
    apps:[{key:'opend',name:'富途 OpenD',installed:true,paths:['C:/FutuOpenD_9.3/FutuOpenD.exe'],running:true}],
    guide:[{step:1,title:'下载并解压 OpenD',detail:'去富途 OpenAPI 官网下载 FutuOpenD(海外版叫 moomooOpenD)。'},
           {step:2,title:'启动 OpenD 并登录',detail:'在 OpenD 自己的窗口里输入富途账号密码。本软件不接触、也不保存你的富途凭证。'},
           {step:5,title:'确认行情权限',detail:'富途的美股行情要单独开通:LV1 够用报价与 K 线,多档盘口要 LV2,期权链还要单独的美股期权行情权限。'}],
    connections:{opend:{host:'127.0.0.1',port:11111}}, connected:['opend'], active:true, sdk_installed:true}),
  diagnoseFutu: async () => ({results:[{connection:'opend',broker:'futu',host:'127.0.0.1',port:11111,
    port_open:true,port_latency_ms:14,connected:true,server_version:'1010',
    server_time:'2026-08-21 09:42:03',qot_logined:true,trd_logined:true,
    accounts:[{alias:'富途模拟',account_masked:'20***585',is_paper:true,connection:'opend',
      resolved:true,trd_env:'SIMULATE',env_matches:true,default:false}],
    unmapped_accounts:[],unlock_required:false,error:null,hint:null}]}),
  launchFutu: async()=>({launched:true}), setFutuPassword: async()=>({ok:true}),
  unlockFutu: async()=>({unlocked:['opend'],failed:{}}), installFutuSdk: async()=>({installed:[]}),
  submit: async () => ({submitted:[],queued:[],validated_only:[{intent_summary:'限价 316 买入 100 股 AAPL',
    account:'富途模拟', account_masked:'20***585', is_paper:true,notional:31600,warnings:['敞口 31600 USD 超过单笔上限 5000 USD']}],
    rejections:[],warnings:[],llm:{model:'claude-opus-5',latency_ms:2410,
    usage:{input_tokens:3120,output_tokens:210}},executed:false}),
  patchSettings: async()=>({}), setApiKey: async()=>({}),
  connectBroker: async()=>({provider:'futu',connected:['opend'],failed:{},listeners:0}),
  disconnectBroker: async()=>({connected:[]}), halt: async()=>({engaged:true,cancelled:0}),
  resume: async()=>({engaged:false}), exportData: async()=>({}), restartEngine: async()=>({}),
  // params 是 dict 不是数组(见 backtest.STRATEGIES),param_labels 给界面显示中文名
  backtestStrategies: async () => ({strategies:[
    {key:'buy_hold',label:'买入持有',desc:'第一天买入,一直持有到区间结束。是所有策略的基准。',
     params:{}, param_labels:{}},
    {key:'sma_cross',label:'均线交叉',desc:'快线上穿慢线持有,下穿空仓。',
     params:{fast:10,slow:50}, param_labels:{fast:'快线周期(日)',slow:'慢线周期(日)'}},
    {key:'rsi',label:'RSI 超卖买入',desc:'RSI 跌破买入线建仓,升破卖出线离场。',
     params:{period:14,buy_below:30,sell_above:70},
     param_labels:{period:'RSI 周期(日)',buy_below:'跌破这个值买入',sell_above:'升破这个值卖出'}}]}),
  runBacktest: async()=>({trades:[],stats:{}}), parseBacktestRules: async()=>({}),
  orderBook: async () => ({symbol:'SPY',l1:{bid:766.8,ask:766.81,bid_size:15,ask_size:230,
    last:766.74,spread:0.01,spread_bps:0.1},
    bids:[{price:766.80,size:15},{price:766.79,size:420},{price:766.78,size:1100},
          {price:766.77,size:860},{price:766.76,size:2300}],
    asks:[{price:766.81,size:230},{price:766.82,size:540},{price:766.83,size:980},
          {price:766.84,size:1420},{price:766.85,size:1900}],
    note:'', liquidity:{spread_bps:0.1,spread_grade:'很好',bid_depth:4695,ask_depth:5070,
      levels:5,imbalance_pct:-3.8}}),
  optionWall: async () => { throw new Error('富途返回「没有美股期权行情权限」。这份权限和股票行情是分开的。'); },
  listAlerts: async () => ({watches:[{id:'w1',symbol:'SPY',step:5,enabled:1,last_price:766.78,
    expiry:'',wall:null,levels:[
      {price:765,label:'整数关口',source:'round',kind:'support',state:{armed:true}},
      {price:770,label:'整数关口',source:'round',kind:'resistance',state:{armed:true}}]}]}),
  createAlert: async()=>({}), deleteAlert: async()=>({}), refreshAlert: async()=>({}),
  pollAlerts: async()=>({fired:[],checked:[]}),
  paTimeframes: async () => ({timeframes:[{key:'1m',label:'1 分钟'},{key:'5m',label:'5 分钟'},
    {key:'15m',label:'15 分钟'},{key:'30m',label:'30 分钟'},{key:'1h',label:'1 小时'},{key:'1d',label:'日线'}]}),
  paAnalyze: async()=>({}), paComment: async()=>({}),
  macroBoard: async () => MACRO,
  // 持仓追踪:一多一空、一个正股一个期权,覆盖盈亏正负两侧
  listPositions: async () => ({positions:[
    {key:'富途模拟|NVDA|STK', account:'富途模拟', symbol:'NVDA', sec_type:'STK',
     quantity:100, avg_cost:180.0, multiplier:1, currency:'USD',
     market_price:219.74, market_value:21974, unrealized_pnl:3974, tracked:true,
     contract:{secType:'STK',symbol:'NVDA',exchange:'SMART',currency:'USD'}},
    {key:'富途模拟|TSLA|STK', account:'富途模拟', symbol:'TSLA', sec_type:'STK',
     quantity:-50, avg_cost:400.0, multiplier:1, currency:'USD',
     market_price:412.30, market_value:-20615, unrealized_pnl:-615, tracked:false,
     contract:{secType:'STK',symbol:'TSLA',exchange:'SMART',currency:'USD'}},
    {key:'富途模拟|AAPL|OPT', account:'富途模拟', symbol:'AAPL', sec_type:'OPT',
     quantity:2, avg_cost:550.0, multiplier:100, currency:'USD',
     market_price:6.20, market_value:1240, unrealized_pnl:140, tracked:false,
     contract:{secType:'OPT',symbol:'AAPL',exchange:'SMART',currency:'USD',
               lastTradeDateOrContractMonth:'20260918',strike:320,right:'C',multiplier:'100'}}]}),
  listTrackers: async () => ({tracks:[
    {id:'tk1', created_at:'2026-08-21T13:00:00Z', updated_at:'2026-08-21T13:30:00Z',
     account:'富途模拟', symbol:'NVDA', sec_type:'STK',
     contract:{secType:'STK',symbol:'NVDA'},
     targets:{take_profit:240.0, stop_loss:200.0, trail_pct:5},
     auto_close:{enabled:true, order_type:'MKT', slippage_pct:0.3},
     enabled:true, peak:225.0, fired_at:null, fired_state:'', fired_record:'', note:''}]}),
  addTracker: async()=>({}), updateTracker: async()=>({}),
  deleteTracker: async()=>({}), closePositionNow: async()=>({fired:{reason:'手动平仓'}}),
  pollTrackers: async () => ({rows:[
    {id:'tk1', state:'holding', price:219.74, peak:225.0, trail_stop:213.75,
     unrealized_pnl:3974, unrealized_pct:22.08, reason:'', stop_effective:213.75}],
    fired:[], blocked:[]}),
  setTheme: async()=>({}), pickExportPath: async()=>null,
  confirm: async()=>true, notify: async()=>({}),
  on: () => () => {},
};

